### ISSUE TITLE
Pawn HEX not processed

### ISSUE THREAD

**Issue by rlogiacco** [PetteriAimonen/QuadPawn#15]
I've got a DSO quad with SYS 1.62, FPGA 2.81 and APP 1.10, I installed successfully your LOGIC ANALYZER as app 3, but I can't do anything with PAWN011B: the file upload completes, but there is no processing of the HEX file and the device doesn't disconnect to process the just uploaded file. Do you have any suggestion?
What I did notice is that the file seems to be uploaded immediately compared to the upload of the logic analizer hex which was smaller but did took some time and a progress meter.

My DFU disk shows up as a 2MB drive and I didn't upload any alternate firmware (the DFU screen shows a V3.40C firmware version).

I tried the previous version (0.11 and 0.10) but in that case the upload process just hangs for a while and ends up with the DFU disk getting removed.

**Comment by PetteriAimonen** [comment]
Sorry, but it works on my hardware and debugging without having the 
problematic hardware is so tedious that I'm not interested in doing 
that.

**Comment by rlogiacco** [comment]
I do perfectly understand :+1: I was just hoping you might have some suggestion. I will keep trying as some of your apps look quite interesting.

Thanks anyway for your time :santa:
